# Generated by Django 4.2.16 on 2026-05-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avg_diameter', models.FloatField()),
                ('velocity', models.FloatField()),
                ('miss_distance', models.FloatField()),
                ('hazardous', models.BooleanField(default=False)),
                ('risk', models.IntegerField(default=0)),
                ('source', models.CharField(default='SBDB CSV', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
